package view;

import controller.Controller;
import model.*;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.stream.Collectors;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 * * The main class for the GUI view
 * * Whole GUI is handled from this class
 *
 * @author Korwin Bieniek
 * @version 1.1.0
 */
public class GraphicalUserInterface extends JFrame {

    private final JTextField numbersField;
    private final JTextField resultField;
    private static Container container = new Container();
    private final GuiExceptions exceptions = new GuiExceptions();
    JTable results;
    DefaultTableModel model;
    NWD nwd = new NWD();
    NWW nww = new NWW();
    ArrayList<Integer> args = null;
    int listLength = 0;

    /**
     * @return returns a Content Pane
     */
    public static Container getContainer() {
        return container;
    }

    /**
     * The constructor for GUI panel
     */
    public GraphicalUserInterface(ArrayList<Integer> nums, int length) {

        args = nums;
        listLength = length;
        container = getContentPane();
        container.setLayout(new FlowLayout());

        String values = args.stream().map(Object::toString)
                .collect(Collectors.joining(", "));

        Panel firstPanel = new Panel();
        Panel secondButton = new Panel();
        Panel thirdPanel = new Panel();
        firstPanel.setLayout(new FlowLayout());

        JButton nwwButton = new JButton("NWW");
        JButton nwdButton = new JButton("NWD");
        model = new DefaultTableModel();

        results = new JTable(model);
        results.setDefaultEditor(Object.class, null);
        TableColumnModel columnModel = results.getColumnModel();


        model.addColumn("Numbers");
        model.addColumn("Result");

        model.addRow(new Object[]{model.getColumnName(0), model.getColumnName(1)});

        columnModel.getColumn(0).setMinWidth(200);

        JLabel numberLabel = new JLabel("Numbers");
        JLabel resultLabel = new JLabel("Result");

        numbersField = new JTextField();
        numbersField.setColumns(8);

        resultField = new JTextField();
        resultField.setColumns(8);
        resultField.setEditable(false);

        thirdPanel.add(firstPanel);
        thirdPanel.add(secondButton);

        firstPanel.add(numberLabel);
        firstPanel.add(numbersField);
        firstPanel.add(resultLabel);
        firstPanel.add(resultField);

        numbersField.setText(values);

        secondButton.add(nwwButton);
        secondButton.add(nwdButton);

        container.add(firstPanel);
        container.add(secondButton);
        container.add(thirdPanel);
        container.add(results);

        nwwButton.addActionListener(this::handleNwwButtonClick);
        nwdButton.addActionListener(this::handleNwdButtonClick);
        firstPanel.setLayout(new GridLayout(4, 4));
        nwwButton.setMaximumSize(new Dimension(40, 40));
        nwdButton.setMaximumSize(new Dimension(40, 40));

        setSize(300, 500);
        setVisible(true);
    }

    /**
     * @return arrayList that has been prepared to be used in the GUI
     */
    private ArrayList<Integer> prepareList() {
        String[] preparsedList = numbersField.getText().split(", ");
        ArrayList<Integer> arrayList = new ArrayList<>();
        try {
            for (String s : preparsedList) {
                arrayList.add(Integer.parseInt(s));
            }
        } catch (NumberFormatException numberFormatException) {
            exceptions.showNumberFormatWarning();
        }
        return arrayList;
    }

    /**
     * @param actionEvent This event is generated by a Button when the component-specific action occurs (such as being pressed)
     */
    private void handleNwwButtonClick(ActionEvent actionEvent) {
        ArrayList<Integer> arrayList = prepareList();
        try {
            String values = arrayList.stream().map(Object::toString)
                    .collect(Collectors.joining(", "));
            int result = nww.leastCommonMultiplier(listLength, args.size(), arrayList);

            this.resultField.setText(String.valueOf(result));
            model.addRow(new Object[]{"NWW " + values, result});
        } catch (NotEnoughArgumentsException notEnoughArgumentsException) {
            exceptions.showNotEnoughArgumentsWarning();
        }

    }

    /**
     * @param actionEvent This event is generated by a Button when the component-specific action occurs (such as being pressed)
     */
    private void handleNwdButtonClick(ActionEvent actionEvent) {
        ArrayList<Integer> arrayList = prepareList();

        try {
            int result = nwd.greatestCommonDivisorForArray(listLength, args.size(), arrayList);
            this.resultField.setText(String.valueOf(result));
            String values = arrayList.stream().map(Object::toString)
                    .collect(Collectors.joining(", "));
            model.addRow(new Object[]{"NWD " + values, result});
        } catch (NotEnoughArgumentsException notEnoughArgumentsException) {
            exceptions.showNotEnoughArgumentsWarning();
        }

    }


}